version: '3.8'
services:
  postgresql:
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=youneverguessevenifwouldgonnatry
      - POSTGRES_USER=mrtotalsecurity
      - POSTGRES_PASSWORD=vZJYfmq7z8A)~c@C^)3L%PR~DdK2Vm*I
